/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Native VantaDB handle exposed to Node.js. Thin wrapper over the SDK's
 * `VantaEmbedded`; all engine methods are async to avoid blocking the JS thread.
 */
export declare class VantaDb {
  /**
   * Open (or create) a VantaDB database at `path`.
   *
   * `path` may be a filesystem directory (persistent, fjall backend) or
   * `":memory:"` for a non-persistent in-memory database.
   *
   * `options` (optional): `{ read_only?: boolean, memory_limit?: number }`.
   */
  static connect(path: string, options?: any | undefined | null): Promise<VantaDb>
  /** Flush the WAL and memory-mapped files to disk. */
  flush(): Promise<void>
  /**
   * Close the database handle. Pending writes are flushed first.
   *
   * Once closing starts, new operations are rejected (`database is
   * closing`). This waits for every in-flight operation to finish before
   * flushing, so a fire-and-forget `put` whose `spawn_blocking` had not yet
   * run can never write after `close()` returns and be silently lost on
   * process exit.
   */
  close(): Promise<void>
  /**
   * Insert or update a persistent memory record.
   *
   * `record`: `{ namespace, key, payload, metadata?, vector?, ttl_ms? }`.
   * Returns the created/updated record with system timestamps and version.
   */
  put(record: any): Promise<any>
  /** Insert or update multiple records. Returns the resulting records. */
  putBatch(records: any): Promise<any>
  /** Retrieve a memory record by namespace and key. Returns `null` if absent. */
  get(namespace: string, key: string): Promise<any | null>
  /**
   * Delete a memory record by namespace and key. Returns `true` if a record
   * was actually deleted, `false` if it did not exist.
   */
  delete(namespace: string, key: string): Promise<boolean>
  /**
   * List records in a namespace with optional filters and cursor pagination.
   *
   * `options` (optional): `{ filters?: VantaMetadata, limit?: number, cursor?: number }`.
   * Returns `{ records: MemoryRecord[], next_cursor?: number }`.
   */
  list(namespace: string, options?: any | undefined | null): Promise<any>
  /** Return all namespaces that contain at least one memory record. */
  listNamespaces(): Promise<Array<string>>
  /**
   * Search memory records by vector similarity (with optional filters and
   * text query). Returns hits ordered by relevance: each hit is
   * `{ record: MemoryRecord, score: number, explanation?: object }`.
   */
  search(request: any): Promise<any>
  /** Return stable runtime capabilities. */
  capabilities(): any
}
export type VantaDB = VantaDb
